#!/usr/bin/env tsx
/**
 * ATOM Figma Pull — Fetch tokens from any Figma file
 *
 * Usage:
 *   pnpm figma:pull <url>                               Pull via REST API (Enterprise)
 *   pnpm figma:pull --data <path.json>                  Pull from pre-extracted MCP data
 *   pnpm figma:pull --data <path.json> --backup         Create backup before writing
 *   pnpm figma:pull --data <path.json> --dry-run        Preview changes without writing
 *   pnpm figma:pull --data <path.json> --yes            Skip confirmation prompt
 *   pnpm figma:pull --data <path.json> --backup --yes   Backup + auto-confirm
 *
 * The --data flag accepts a JSON file generated by Claude Code via
 * Figma MCP (use_figma Plugin API), bypassing the REST API entirely.
 * This works on ALL Figma plans — no Enterprise required.
 */

import React, { useState, useEffect } from 'react'
import { render, Box, Text, useApp, useInput } from 'ink'
import Spinner from 'ink-spinner'
import { readFileSync, writeFileSync, copyFileSync, existsSync, mkdirSync } from 'fs'
import { resolve, dirname } from 'path'
import { fileURLToPath } from 'url'
import { execSync } from 'child_process'
import { PassThrough } from 'stream'

const __filename = fileURLToPath(import.meta.url)
const __dirname = dirname(__filename)

// ── Config ──────────────────────────────────────────────────────────

const TOKENS_BASE = resolve(__dirname, '../../../packages/tokens/src/figma')
const PREFERRED_MODES = ['Light', 'Base', 'Default']

// ── Types ───────────────────────────────────────────────────────────

interface FigmaVariable {
  id: string
  name: string
  resolvedType: 'COLOR' | 'FLOAT' | 'STRING' | 'BOOLEAN'
  valuesByMode: Record<string, FigmaVariableValue>
  variableCollectionId: string
  description: string
  hiddenFromPublishing: boolean
}

interface FigmaVariableCollection {
  id: string
  name: string
  modes: Array<{ modeId: string; name: string }>
  defaultModeId: string
  variableIds: string[]
}

type FigmaVariableValue =
  | { r: number; g: number; b: number; a: number }
  | number
  | string
  | boolean
  | { type: 'VARIABLE_ALIAS'; id: string }

interface FigmaVariablesResponse {
  status: number
  error: boolean
  meta: {
    variables: Record<string, FigmaVariable>
    variableCollections: Record<string, FigmaVariableCollection>
  }
}

// ── MCP Data Format ─────────────────────────────────────────────────

interface McpVariable {
  name: string
  type: string
  value: string | number | boolean
  alias?: string
}

interface McpCollection {
  name: string
  variables: McpVariable[]
}

interface McpData {
  fileName: string
  collections: McpCollection[]
}

// ── Merge Types ─────────────────────────────────────────────────────

interface MergeChange {
  path: string
  type: 'added' | 'updated'
  oldValue?: string
  newValue: string
}

interface CollectionResult {
  collectionName: string
  fileName: string
  filePath: string
  isNewFile: boolean
  merged: Record<string, unknown>
  changes: MergeChange[]
  tokenCount: number
}

type AppPhase =
  | { step: 'fetching'; message: string }
  | { step: 'summary'; fileName: string; fileKey: string; collections: CollectionResult[]; totalAdded: number; totalUpdated: number }
  | { step: 'confirm'; collections: CollectionResult[] }
  | { step: 'writing' }
  | { step: 'done'; written: number; gitDiff: string; backupPath?: string }
  | { step: 'error'; message: string }

// ── URL Parsing ─────────────────────────────────────────────────────

function parseFileKey(input: string): string {
  if (/^[a-zA-Z0-9]{10,}$/.test(input)) return input

  const match = input.match(/figma\.com\/(?:design|file)\/([a-zA-Z0-9]+)/)
  if (match) return match[1]

  throw new Error(
    `Could not extract file key from: ${input}\n` +
    'Expected: https://www.figma.com/design/<key>/... or a raw file key'
  )
}

// ── Token Loading ───────────────────────────────────────────────────

function loadFigmaToken(): string {
  if (process.env.FIGMA_TOKEN) return process.env.FIGMA_TOKEN

  const envPaths = [
    resolve(__dirname, '../../../.env.figma'),
    resolve(__dirname, '../.env'),
  ]

  for (const envPath of envPaths) {
    if (existsSync(envPath)) {
      const content = readFileSync(envPath, 'utf-8')
      const match = content.match(/^FIGMA_TOKEN=(.+)$/m)
      if (match && match[1].trim() && !match[1].startsWith('#')) {
        return match[1].trim()
      }
    }
  }

  throw new Error(
    'FIGMA_TOKEN not found.\n\n' +
    'Set it via:\n' +
    '  export FIGMA_TOKEN=figd_xxx\n' +
    '  or add to .env.figma in monorepo root\n\n' +
    'Get your token at: https://www.figma.com/settings'
  )
}

// ── Figma API ───────────────────────────────────────────────────────

async function fetchFileMetadata(fileKey: string, token: string): Promise<{ name: string }> {
  const response = await fetch(`https://api.figma.com/v1/files/${fileKey}?depth=1`, {
    headers: { 'X-Figma-Token': token },
  })

  if (!response.ok) {
    const text = await response.text()
    throw new Error(apiErrorMessage(response.status, text))
  }

  const data = await response.json() as { name: string }
  return { name: data.name }
}

async function fetchVariables(fileKey: string, token: string): Promise<FigmaVariablesResponse> {
  const response = await fetch(`https://api.figma.com/v1/files/${fileKey}/variables/local`, {
    headers: { 'X-Figma-Token': token },
  })

  if (!response.ok) {
    const text = await response.text()
    throw new Error(apiErrorMessage(response.status, text))
  }

  return response.json() as Promise<FigmaVariablesResponse>
}

function apiErrorMessage(status: number, body: string): string {
  const messages: Record<number, string> = {
    401: 'Authentication failed. Check your FIGMA_TOKEN.',
    403: 'Access denied. Ensure your token has file:read scope and the Variables API is available on your plan (Professional+).',
    404: 'File not found. Check the URL.',
    429: 'Rate limited by Figma API. Wait a moment and try again.',
  }
  return messages[status] ?? `Figma API error ${status}: ${body.slice(0, 200)}`
}

// ── Transform ───────────────────────────────────────────────────────

/**
 * Map Figma FLOAT to the correct W3C DTCG type based on collection semantics.
 * Figma only has FLOAT/COLOR/STRING/BOOLEAN — DTCG is more specific.
 */
const COLLECTION_TYPE_MAP: Record<string, string> = {
  spacing: 'dimension',
  radius: 'dimension',
  stroke: 'dimension',
  breakpoints: 'dimension',
  opacity: 'number',
  typography: 'number',
}

function resolveDtcgType(figmaType: string, collectionName: string): string {
  const rawType = figmaType.toLowerCase()
  if (rawType === 'color') return 'color'
  if (rawType === 'boolean') return 'boolean'
  if (rawType === 'string') return 'string'
  // FLOAT → look up by collection name
  const colKey = collectionName.toLowerCase()
  return COLLECTION_TYPE_MAP[colKey] ?? 'number'
}

function rgbaToHex({ r, g, b, a = 1 }: { r: number; g: number; b: number; a?: number }): string {
  const toHex = (n: number): string => {
    const hex = Math.round(n * 255).toString(16).toUpperCase()
    return hex.length === 1 ? '0' + hex : hex
  }
  const hex = `#${toHex(r)}${toHex(g)}${toHex(b)}`
  return a < 1 ? `${hex}${toHex(a)}` : hex
}

function pickModeId(collection: FigmaVariableCollection): string {
  for (const preferred of PREFERRED_MODES) {
    const mode = collection.modes.find(m =>
      m.name.toLowerCase() === preferred.toLowerCase()
    )
    if (mode) return mode.modeId
  }
  return collection.defaultModeId
}

function transformValue(
  rawValue: FigmaVariableValue,
  variable: FigmaVariable,
  allVariables: Record<string, FigmaVariable>,
  allCollections: Record<string, FigmaVariableCollection>,
  collectionName: string,
): { value: string | number | boolean; type: string } {
  const type = resolveDtcgType(variable.resolvedType, collectionName)

  // Alias reference
  if (typeof rawValue === 'object' && rawValue !== null && 'type' in rawValue && rawValue.type === 'VARIABLE_ALIAS') {
    const aliasVar = allVariables[rawValue.id]
    if (aliasVar) {
      const aliasCollection = allCollections[aliasVar.variableCollectionId]
      const collectionKey = sanitizeFileName(aliasCollection?.name ?? 'unknown')
      const aliasPath = aliasVar.name
        .split('/')
        .map((p: string) => p.toLowerCase().replace(/\s+/g, '-'))
        .join('.')
      return { value: `{figma.${collectionKey}.${aliasPath}}`, type }
    }
    return { value: `{alias:${rawValue.id}}`, type }
  }

  // Color
  if (type === 'color' && typeof rawValue === 'object' && rawValue !== null && 'r' in rawValue) {
    return { value: rgbaToHex(rawValue as { r: number; g: number; b: number; a?: number }), type }
  }

  return { value: rawValue as string | number | boolean, type }
}

function transformCollection(
  figmaData: FigmaVariablesResponse,
  collectionId: string,
): Record<string, unknown> {
  const { variables, variableCollections } = figmaData.meta
  const collection = variableCollections[collectionId]
  const modeId = pickModeId(collection)
  const tokens: Record<string, unknown> = {}

  for (const varId of collection.variableIds) {
    const variable = variables[varId]
    if (!variable || variable.hiddenFromPublishing) continue

    const rawValue = variable.valuesByMode[modeId]
    if (rawValue === undefined) continue

    const path = variable.name
      .split('/')
      .map((part: string) => part.toLowerCase().replace(/\s+/g, '-'))

    const { value, type } = transformValue(rawValue, variable, variables, variableCollections, collection.name)

    const tokenData: Record<string, unknown> = { $type: type, $value: value }
    if (variable.description) tokenData.$description = variable.description

    // Build nested structure
    let current: Record<string, unknown> = tokens
    for (let i = 0; i < path.length; i++) {
      if (i === path.length - 1) {
        current[path[i]] = tokenData
      } else {
        if (!current[path[i]] || typeof current[path[i]] !== 'object') {
          current[path[i]] = {}
        }
        current = current[path[i]] as Record<string, unknown>
      }
    }
  }

  return tokens
}

// ── MCP Transform ───────────────────────────────────────────────────

function transformMcpCollection(collection: McpCollection): Record<string, unknown> {
  const tokens: Record<string, unknown> = {}

  for (const variable of collection.variables) {
    const path = variable.name
      .split('/')
      .map((part: string) => part.toLowerCase().replace(/\s+/g, '-'))

    const type = resolveDtcgType(variable.type, collection.name)

    // Prefer alias reference; fall back to resolved value
    const value = variable.alias
      ? variable.alias.replace(/\{([^}]+)\}/g, (_: string, inner: string) =>
          `{${inner.split('.').map((s: string) => s.toLowerCase().replace(/\s+/g, '-')).join('.')}}`)
      : variable.value

    const tokenData: Record<string, unknown> = { $type: type, $value: value }

    // Build nested structure
    let current: Record<string, unknown> = tokens
    for (let i = 0; i < path.length; i++) {
      if (i === path.length - 1) {
        current[path[i]] = tokenData
      } else {
        if (!current[path[i]] || typeof current[path[i]] !== 'object') {
          current[path[i]] = {}
        }
        current = current[path[i]] as Record<string, unknown>
      }
    }
  }

  return tokens
}

// ── Merge (from sync-from-clipboard.js) ─────────────────────────────

function sanitizeFileName(name: string): string {
  return name
    .toLowerCase()
    .replace(/[\s/]+/g, '-')
    .replace(/-+/g, '-')
    .replace(/^-|-$/g, '')
}

function countTokens(obj: Record<string, unknown>): number {
  let count = 0
  for (const [key, value] of Object.entries(obj)) {
    if (key.startsWith('$')) continue
    if (typeof value === 'object' && value !== null) {
      if ('$value' in value) count++
      else count += countTokens(value as Record<string, unknown>)
    }
  }
  return count
}

function mergeTokens(
  existing: Record<string, unknown>,
  incoming: Record<string, unknown>,
  path: string[] = [],
): { result: Record<string, unknown>; changes: MergeChange[] } {
  const result = { ...existing }
  const changes: MergeChange[] = []

  for (const [key, incomingValue] of Object.entries(incoming)) {
    const currentPath = [...path, key]
    const pathStr = currentPath.join('.')

    if (!(key in result)) {
      result[key] = incomingValue
      if (typeof incomingValue === 'object' && incomingValue !== null && '$value' in incomingValue) {
        changes.push({ path: pathStr, type: 'added', newValue: String((incomingValue as Record<string, unknown>).$value) })
      } else if (typeof incomingValue === 'object' && incomingValue !== null) {
        collectLeaves(incomingValue as Record<string, unknown>, currentPath).forEach(leaf => {
          changes.push({ path: leaf.path, type: 'added', newValue: String(leaf.value) })
        })
      }
      continue
    }

    const existingValue = result[key]

    if (
      typeof incomingValue === 'object' && incomingValue !== null &&
      typeof existingValue === 'object' && existingValue !== null &&
      '$value' in incomingValue && '$value' in existingValue
    ) {
      const inc = incomingValue as Record<string, unknown>
      const ext = existingValue as Record<string, unknown>
      if (String(inc.$value) !== String(ext.$value)) {
        changes.push({ path: pathStr, type: 'updated', oldValue: String(ext.$value), newValue: String(inc.$value) })
        result[key] = { ...ext, ...inc }
      }
      continue
    }

    if (
      typeof incomingValue === 'object' && incomingValue !== null &&
      typeof existingValue === 'object' && existingValue !== null &&
      !('$value' in incomingValue) && !('$value' in existingValue)
    ) {
      const nested = mergeTokens(
        existingValue as Record<string, unknown>,
        incomingValue as Record<string, unknown>,
        currentPath,
      )
      result[key] = nested.result
      changes.push(...nested.changes)
      continue
    }

    if (JSON.stringify(existingValue) !== JSON.stringify(incomingValue)) {
      changes.push({ path: pathStr, type: 'updated', oldValue: JSON.stringify(existingValue), newValue: JSON.stringify(incomingValue) })
      result[key] = incomingValue
    }
  }

  return { result, changes }
}

function collectLeaves(obj: Record<string, unknown>, basePath: string[] = []): Array<{ path: string; value: unknown }> {
  const leaves: Array<{ path: string; value: unknown }> = []
  for (const [key, value] of Object.entries(obj)) {
    if (key.startsWith('$')) continue
    const p = [...basePath, key]
    if (typeof value === 'object' && value !== null) {
      if ('$value' in value) {
        leaves.push({ path: p.join('.'), value: (value as Record<string, unknown>).$value })
      } else {
        leaves.push(...collectLeaves(value as Record<string, unknown>, p))
      }
    }
  }
  return leaves
}

function syncCollection(collectionName: string, tokens: Record<string, unknown>, targetDir: string): CollectionResult {
  const fileName = `${sanitizeFileName(collectionName)}.json`
  const filePath = resolve(targetDir, fileName)

  if (!existsSync(targetDir)) {
    mkdirSync(targetDir, { recursive: true })
  }

  let existing: Record<string, unknown> = {}
  let isNewFile = true

  if (existsSync(filePath)) {
    try {
      existing = JSON.parse(readFileSync(filePath, 'utf-8'))
      isNewFile = false
    } catch {
      // Corrupted file — treat as new
    }
  }

  const { result: merged, changes } = mergeTokens(existing, tokens)

  return {
    collectionName,
    fileName,
    filePath,
    isNewFile,
    merged,
    changes,
    tokenCount: countTokens(tokens),
  }
}

// ── Ink Components ──────────────────────────────────────────────────

function Header(): React.ReactElement {
  return (
    <Box flexDirection="column" marginBottom={1}>
      <Text bold color="cyan">ATOM Figma Pull</Text>
    </Box>
  )
}

function FetchingView({ message }: { message: string }): React.ReactElement {
  return (
    <Box gap={1}>
      <Text color="yellow"><Spinner type="dots" /></Text>
      <Text>{message}</Text>
    </Box>
  )
}

function CollectionRow({ result, folderName }: { result: CollectionResult; folderName: string }): React.ReactElement {
  const added = result.changes.filter(c => c.type === 'added').length
  const updated = result.changes.filter(c => c.type === 'updated').length
  const hasChanges = added > 0 || updated > 0 || result.isNewFile

  return (
    <Box flexDirection="column" marginBottom={hasChanges ? 1 : 0}>
      <Box gap={1}>
        <Text bold>{result.collectionName}</Text>
        <Text dimColor>→</Text>
        <Text color="cyan">{folderName}/{result.fileName}</Text>
        {result.isNewFile && <Text color="green" bold>NEW</Text>}
        <Text dimColor>({result.tokenCount} tokens,</Text>
        {added + updated > 0 ? (
          <Text color="yellow">{added + updated} changes</Text>
        ) : (
          <Text dimColor>no changes</Text>
        )}
        <Text dimColor>)</Text>
      </Box>

      {/* Show top 5 changes */}
      {result.changes.slice(0, 5).map((change, i) => (
        <Box key={i} marginLeft={2} flexDirection="column">
          {change.type === 'added' ? (
            <Text>
              <Text color="green">+ </Text>
              <Text dimColor>{change.path}</Text>
              <Text> = </Text>
              <Text color="green">{change.newValue}</Text>
            </Text>
          ) : (
            <Box flexDirection="column">
              <Text>
                <Text color="yellow">~ </Text>
                <Text dimColor>{change.path}</Text>
              </Text>
              <Box marginLeft={4} flexDirection="column">
                <Text><Text color="red">- {change.oldValue}</Text></Text>
                <Text><Text color="green">+ {change.newValue}</Text></Text>
              </Box>
            </Box>
          )}
        </Box>
      ))}
      {result.changes.length > 5 && (
        <Box marginLeft={2}>
          <Text dimColor>  ...and {result.changes.length - 5} more</Text>
        </Box>
      )}
    </Box>
  )
}

function SummaryView({ fileName, fileKey, collections, totalAdded, totalUpdated, folderName }: {
  fileName: string
  fileKey: string
  collections: CollectionResult[]
  totalAdded: number
  totalUpdated: number
  folderName: string
}): React.ReactElement {
  return (
    <Box flexDirection="column" gap={1}>
      <Box flexDirection="column">
        <Box gap={1}>
          <Text dimColor>File:</Text>
          <Text bold>"{fileName}"</Text>
          <Text dimColor>({fileKey})</Text>
        </Box>
        <Box gap={1}>
          <Text dimColor>Target:</Text>
          <Text color="cyan">packages/tokens/src/figma/{folderName}/</Text>
        </Box>
      </Box>

      <Box flexDirection="column">
        <Box marginBottom={1}>
          <Text bold color="cyan">Collections:</Text>
        </Box>
        {collections.map((col, i) => (
          <CollectionRow key={i} result={col} folderName={folderName} />
        ))}
      </Box>

      <Box gap={1}>
        <Text bold>Summary:</Text>
        <Text color="green">+{totalAdded} added</Text>
        <Text dimColor>,</Text>
        <Text color="yellow">~{totalUpdated} updated</Text>
        <Text dimColor>, 0 deleted (never)</Text>
      </Box>
    </Box>
  )
}

function ConfirmPrompt({ onConfirm, onCancel }: { onConfirm: () => void; onCancel: () => void }): React.ReactElement {
  useInput((input) => {
    if (input.toLowerCase() === 'y') onConfirm()
    else if (input.toLowerCase() === 'n' || input === '\r' || input === '\x1B') onCancel()
  })

  return (
    <Box gap={1} marginTop={1}>
      <Text color="yellow" bold>Apply changes?</Text>
      <Text dimColor>(y/N)</Text>
    </Box>
  )
}

function DoneView({ written, gitDiff, backupPath, folderName }: { written: number; gitDiff: string; backupPath?: string; folderName: string }): React.ReactElement {
  return (
    <Box flexDirection="column" gap={1} marginTop={1}>
      <Text color="green" bold>Done! {written} files written.</Text>

      {backupPath && (
        <Box flexDirection="column" marginTop={1}>
          <Text bold color="yellow">Backup:</Text>
          <Text dimColor>  {backupPath}</Text>
        </Box>
      )}

      {gitDiff.trim() && (
        <Box flexDirection="column">
          <Text bold color="cyan">Git:</Text>
          <Text>{gitDiff.trim()}</Text>
        </Box>
      )}

      <Box flexDirection="column">
        <Text bold color="cyan">Next steps:</Text>
        <Text>  1. Review changes in packages/tokens/src/figma/{folderName}/</Text>
        <Text>  2. cd packages/tokens && pnpm build</Text>
        <Text>  3. Test your app</Text>
      </Box>
    </Box>
  )
}

function ErrorView({ message }: { message: string }): React.ReactElement {
  return (
    <Box flexDirection="column" marginTop={1}>
      <Text color="red" bold>Error</Text>
      <Text color="red">{message}</Text>
    </Box>
  )
}

// ── Main App ────────────────────────────────────────────────────────

function App({ url, dryRun, skipConfirm, enableBackup, dataPath }: {
  url?: string
  dryRun: boolean
  skipConfirm: boolean
  enableBackup: boolean
  dataPath?: string
}): React.ReactElement {
  const { exit } = useApp()
  const [phase, setPhase] = useState<AppPhase>({ step: 'fetching', message: 'Loading...' })
  const [folderName, setFolderName] = useState('')
  const [collectionsData, setCollectionsData] = useState<CollectionResult[]>([])

  useEffect(() => {
    runPull().catch((err: Error) => {
      setPhase({ step: 'error', message: err.message })
    })
  }, [])

  async function runPull(): Promise<void> {
    let fileName: string
    let fileKey: string
    let results: CollectionResult[]

    if (dataPath) {
      // ── MCP mode: read pre-extracted data ──
      const pulled = await runMcpPull(dataPath)
      fileName = pulled.fileName
      fileKey = 'mcp'
      results = pulled.results
    } else if (url) {
      // ── REST API mode ──
      const pulled = await runRestPull(url)
      fileName = pulled.fileName
      fileKey = pulled.fileKey
      results = pulled.results
    } else {
      throw new Error('Either a Figma URL or --data <path> is required.')
    }

    const folder = sanitizeFileName(fileName)
    setFolderName(folder)
    setCollectionsData(results)

    const totalAdded = results.reduce((sum, r) => sum + r.changes.filter(c => c.type === 'added').length, 0)
    const totalUpdated = results.reduce((sum, r) => sum + r.changes.filter(c => c.type === 'updated').length, 0)

    if (totalAdded + totalUpdated === 0 && !results.some(r => r.isNewFile)) {
      setPhase({ step: 'summary', fileName, fileKey, collections: results, totalAdded: 0, totalUpdated: 0 })
      setTimeout(() => exit(), 100)
      return
    }

    setPhase({ step: 'summary', fileName, fileKey, collections: results, totalAdded, totalUpdated })

    if (dryRun) {
      setTimeout(() => exit(), 100)
      return
    }

    if (skipConfirm) {
      writeFiles(results, folder)
      return
    }

    setPhase({ step: 'confirm', collections: results })
  }

  async function runMcpPull(path: string): Promise<{ fileName: string; results: CollectionResult[] }> {
    setPhase({ step: 'fetching', message: 'Reading MCP data...' })

    const raw = readFileSync(path, 'utf-8')
    const mcpData: McpData = JSON.parse(raw)
    const fileName = mcpData.fileName

    const varCount = mcpData.collections.reduce((s, c) => s + c.variables.length, 0)
    setPhase({ step: 'fetching', message: `Transforming ${varCount} variables from ${mcpData.collections.length} collections...` })

    const folder = sanitizeFileName(fileName)
    const targetDir = resolve(TOKENS_BASE, folder)
    const results: CollectionResult[] = []

    for (const col of mcpData.collections) {
      const tokens = transformMcpCollection(col)
      if (Object.keys(tokens).length === 0) continue

      const collectionKey = sanitizeFileName(col.name)
      const wrappedTokens = { figma: { [collectionKey]: tokens } }
      const result = syncCollection(col.name, wrappedTokens, targetDir)
      results.push(result)
    }

    return { fileName, results }
  }

  async function runRestPull(inputUrl: string): Promise<{ fileName: string; fileKey: string; results: CollectionResult[] }> {
    const fileKey = parseFileKey(inputUrl)
    const token = loadFigmaToken()

    setPhase({ step: 'fetching', message: `Fetching "${fileKey}"...` })
    const { name: fileName } = await fetchFileMetadata(fileKey, token)

    setPhase({ step: 'fetching', message: `Fetching variables from "${fileName}"...` })
    const figmaData = await fetchVariables(fileKey, token)

    const varCount = Object.keys(figmaData.meta.variables).length
    const collectionCount = Object.keys(figmaData.meta.variableCollections).length

    if (varCount === 0) {
      throw new Error(`No variables found in "${fileName}". Is this a Variables-enabled file?`)
    }

    setPhase({ step: 'fetching', message: `Transforming ${varCount} variables from ${collectionCount} collections...` })

    const folder = sanitizeFileName(fileName)
    const targetDir = resolve(TOKENS_BASE, folder)
    const results: CollectionResult[] = []

    for (const [collectionId, collection] of Object.entries(figmaData.meta.variableCollections)) {
      const tokens = transformCollection(figmaData, collectionId)
      if (Object.keys(tokens).length === 0) continue

      const collectionKey = sanitizeFileName(collection.name)
      const wrappedTokens = { figma: { [collectionKey]: tokens } }
      const result = syncCollection(collection.name, wrappedTokens, targetDir)
      results.push(result)
    }

    return { fileName, fileKey, results }
  }

  function createBackup(results: CollectionResult[], folder: string): string | null {
    // Only backup files that will be modified (not new files)
    const filesToBackup = results.filter(r => existsSync(r.filePath) && (r.changes.length > 0 || r.isNewFile))

    if (filesToBackup.length === 0) return null

    const timestamp = new Date().toISOString().replace(/[:.]/g, '-').slice(0, -5)
    const backupDir = resolve(TOKENS_BASE, folder, `.backup-${timestamp}`)

    mkdirSync(backupDir, { recursive: true })

    for (const r of filesToBackup) {
      if (existsSync(r.filePath)) {
        const backupPath = resolve(backupDir, r.fileName)
        copyFileSync(r.filePath, backupPath)
      }
    }

    return backupDir
  }

  function writeFiles(results: CollectionResult[], folder: string): void {
    setPhase({ step: 'writing' })

    // Create backup if enabled
    let backupPath: string | null = null
    if (enableBackup) {
      backupPath = createBackup(results, folder)
    }

    let written = 0
    for (const r of results) {
      if (r.changes.length === 0 && !r.isNewFile) continue
      writeFileSync(r.filePath, JSON.stringify(r.merged, null, 2) + '\n', 'utf-8')
      written++
    }

    let gitDiff = ''
    try {
      gitDiff = execSync(`git diff --stat ${resolve(TOKENS_BASE, folder)}`, {
        encoding: 'utf-8',
        cwd: resolve(__dirname, '../../..'),
      })
    } catch {
      // Not a git repo
    }

    setPhase({ step: 'done', written, gitDiff, backupPath: backupPath ?? undefined })
    setTimeout(() => exit(), 100)
  }

  function handleConfirm(): void {
    writeFiles(collectionsData, folderName)
  }

  function handleCancel(): void {
    setPhase({ step: 'error', message: 'Cancelled.' })
    setTimeout(() => exit(), 100)
  }

  // Exit on error after render
  useEffect(() => {
    if (phase.step === 'error') {
      setTimeout(() => exit(), 100)
    }
  }, [phase.step])

  return (
    <Box flexDirection="column" padding={1}>
      <Header />

      {phase.step === 'fetching' && <FetchingView message={phase.message} />}

      {phase.step === 'summary' && (
        <Box flexDirection="column">
          <SummaryView
            fileName={phase.fileName}
            fileKey={phase.fileKey}
            collections={phase.collections}
            totalAdded={phase.totalAdded}
            totalUpdated={phase.totalUpdated}
            folderName={folderName}
          />
          {phase.totalAdded + phase.totalUpdated === 0 && (
            <Box marginTop={1}>
              <Text color="green">All files are already up to date.</Text>
            </Box>
          )}
        </Box>
      )}

      {phase.step === 'confirm' && (
        <Box flexDirection="column">
          <SummaryView
            fileName=""
            fileKey=""
            collections={phase.collections}
            totalAdded={collectionsData.reduce((s, r) => s + r.changes.filter(c => c.type === 'added').length, 0)}
            totalUpdated={collectionsData.reduce((s, r) => s + r.changes.filter(c => c.type === 'updated').length, 0)}
            folderName={folderName}
          />
          <ConfirmPrompt onConfirm={handleConfirm} onCancel={handleCancel} />
        </Box>
      )}

      {phase.step === 'writing' && (
        <Box gap={1}>
          <Text color="yellow"><Spinner type="dots" /></Text>
          <Text>Writing files...</Text>
        </Box>
      )}

      {phase.step === 'done' && (
        <DoneView written={phase.written} gitDiff={phase.gitDiff} backupPath={phase.backupPath} folderName={folderName} />
      )}

      {phase.step === 'error' && <ErrorView message={phase.message} />}
    </Box>
  )
}

// ── CLI Entry ───────────────────────────────────────────────────────

function printHelp(): void {
  console.log(`
ATOM Figma Pull — Fetch tokens from any Figma file

Usage:
  pnpm figma:pull <url>                        Pull via REST API (Enterprise)
  pnpm figma:pull --data <path.json>           Pull from MCP-extracted data
  pnpm figma:pull --data <path.json> --dry-run Preview changes without writing
  pnpm figma:pull --data <path.json> --yes     Skip confirmation prompt

Arguments:
  url     Figma file URL or raw file key (REST API mode)

Flags:
  --data <path>   Read from JSON file extracted via Figma MCP Plugin API.
                  Works on ALL Figma plans — no Enterprise required.
  --dry-run       Preview changes without writing files
  --yes           Skip confirmation prompt
  --backup        Create timestamped backup of modified files

Environment:
  FIGMA_TOKEN   Figma Personal Access Token (REST API mode only)
                Get yours at: https://www.figma.com/settings

Examples:
  pnpm figma:pull --data /tmp/figma-semantics.json
  pnpm figma:pull --data /tmp/figma-semantics.json --yes
  FIGMA_TOKEN=figd_xxx pnpm figma:pull https://www.figma.com/design/abc123/MyFile
`)
}

const args = process.argv.slice(2)

if (args.includes('--help') || args.includes('-h') || args.length === 0) {
  printHelp()
  process.exit(0)
}

// Parse flags
const dataIdx = args.indexOf('--data')
const dataPath = dataIdx !== -1 ? args[dataIdx + 1] : undefined
const url = args.find(a => !a.startsWith('--') && a !== dataPath)
const dryRun = args.includes('--dry-run')
const skipConfirm = args.includes('--yes')
const enableBackup = args.includes('--backup')

if (!url && !dataPath) {
  console.error('Error: Figma URL or --data <path> required.\n')
  printHelp()
  process.exit(1)
}

const isTTY = process.stdin.isTTY ?? false
const effectiveSkipConfirm = skipConfirm || !isTTY
const renderOptions = !isTTY ? { stdin: new PassThrough() as any } : {}
render(<App url={url} dryRun={dryRun} skipConfirm={effectiveSkipConfirm} enableBackup={enableBackup} dataPath={dataPath} />, renderOptions)
